# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: community.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ommunity.proto\x12\x04grpc\"\'\n\x07MStatus\x12\x1c\n\x06Status\x18\x01 \x01(\x0e\x32\x0c.grpc.STATUS\"\x1b\n\rSpacesCompact\x12\n\n\x02Id\x18\x01 \x01(\t\"<\n\x13\x43ommunityGetRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0b\n\x03Tag\x18\x03 \x01(\t\"\x84\x01\n\x11\x43ommunityMetaData\x12\n\n\x02Id\x18\x01 \x01(\x03\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0b\n\x03Tag\x18\x03 \x01(\t\x12\x13\n\x0b\x44\x65scription\x18\x04 \x01(\t\x12\x0e\n\x06\x42\x61nner\x18\x05 \x01(\t\x12#\n\x06Spaces\x18\x06 \x03(\x0b\x32\x13.grpc.SpacesCompact*1\n\x08\x44\x45\x46\x41ULTS\x12\x12\n\x0eSTRING_DEFAULT\x10\x00\x12\x11\n\rINT32_DEFAULT\x10\x01*)\n\nNUMBER_NUM\x12\x07\n\x03one\x10\x00\x12\x07\n\x03two\x10\x01\x12\t\n\x05three\x10\x02*<\n\x06STATUS\x12\t\n\x05\x45RROR\x10\x00\x12\r\n\tNOT_FOUND\x10\x01\x12\x10\n\x0cWRONG_FORMAT\x10\x02\x12\x06\n\x02OK\x10\x03\x32\xa2\x02\n\x10\x43ommunityService\x12\x44\n\x0cGetCommunity\x12\x19.grpc.CommunityGetRequest\x1a\x17.grpc.CommunityMetaData\"\x00\x12I\n\x0f\x43ommunitySearch\x12\x19.grpc.CommunityGetRequest\x1a\x17.grpc.CommunityMetaData\"\x00\x30\x01\x12\x43\n\tGetSpaces\x12\x19.grpc.CommunityGetRequest\x1a\x17.grpc.CommunityMetaData\"\x00\x30\x01\x12\x38\n\x0cNewCommunity\x12\x17.grpc.CommunityMetaData\x1a\r.grpc.MStatus\"\x00\x42\x34Z2github.com/abhirajranjan/spaces/community/pkg/grpcb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'community_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z2github.com/abhirajranjan/spaces/community/pkg/grpc'
  _DEFAULTS._serialized_start=292
  _DEFAULTS._serialized_end=341
  _NUMBER_NUM._serialized_start=343
  _NUMBER_NUM._serialized_end=384
  _STATUS._serialized_start=386
  _STATUS._serialized_end=446
  _MSTATUS._serialized_start=25
  _MSTATUS._serialized_end=64
  _SPACESCOMPACT._serialized_start=66
  _SPACESCOMPACT._serialized_end=93
  _COMMUNITYGETREQUEST._serialized_start=95
  _COMMUNITYGETREQUEST._serialized_end=155
  _COMMUNITYMETADATA._serialized_start=158
  _COMMUNITYMETADATA._serialized_end=290
  _COMMUNITYSERVICE._serialized_start=449
  _COMMUNITYSERVICE._serialized_end=739
# @@protoc_insertion_point(module_scope)
